"""empty message

Revision ID: 3ffab6e8a016
Revises: b130db706ee3
Create Date: 2022-10-12 12:34:48.145427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffab6e8a016'
down_revision = 'b130db706ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_add', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_add')
    # ### end Alembic commands ###
