"""empty message

Revision ID: a5a38b206967
Revises: bcf85f21d1fc
Create Date: 2022-10-16 19:17:41.416641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a38b206967'
down_revision = 'bcf85f21d1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    op.drop_column('users', 'opt_secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('opt_secret', sa.VARCHAR(length=16), nullable=True))
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
