"""empty message

Revision ID: bcf85f21d1fc
Revises: 3ffab6e8a016
Create Date: 2022-10-13 15:24:53.781463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf85f21d1fc'
down_revision = '3ffab6e8a016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('opt_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'opt_secret')
    # ### end Alembic commands ###
